### ISSUE TITLE
Please configure Dependabot on This Repository

### ISSUE THREAD

**Issue by tohch4** [kungfulinux/flexibot#56]
As a happy customer of Flexibot, I would like [Dependabot configured to track vulnerable dependencies](https://help.github.com/en/github/managing-security-vulnerabilities/configuring-automated-security-updates) if you could. Thanks! If you need help, let me know, but I am obviously not an admin of this repo. :-)

**Comment by JonHolman** [comment]
you would @tohch4 ... :)

**Comment by xee5ch** [comment]
Seems according to kungfulinux/flexibot#61 this is done now.
